- project:
    check:
      jobs:
        - tox-pep8
        - tox-py27
        - tox-py35
        - tox-py36
        - build-sphinx-docs:
            vars:
              sphinx_python: python3
    gate:
      jobs:
        - tox-pep8
        - tox-py27
        - tox-py35
        - tox-py36
        - build-sphinx-docs:
            vars:
              sphinx_python: python3
