- job:
    name: pbrx-build-container-images
    nodeset: ubuntu-bionic
    required-projects:
      - openstack/pbrx
    pre-run: playbooks/container-images/pre.yaml
    run: playbooks/container-images/run.yaml

- job:
    name: pbrx-build-zuul-containers
    parent: pbrx-build-container-images
    required-projects:
      - openstack-infra/zuul
    vars:
      zuul_work_dir: src/git.openstack.org/openstack-infra/zuul
      pypi_mirror: http://mirror.ca-ymq-1.vexxhost.openstack.org:8080/pypi/simple/

- project:
    check:
      jobs:
        - tox-pep8
        - tox-py35
        - tox-py36:
            nodeset: ubuntu-bionic
        - build-sphinx-docs:
            vars:
              sphinx_python: python3
        - pbrx-build-zuul-containers
    gate:
      jobs:
        - tox-pep8
        - tox-py35
        - tox-py36:
            nodeset: ubuntu-bionic
        - build-sphinx-docs:
            vars:
              sphinx_python: python3
        - pbrx-build-zuul-containers
