- job:
    name: pbrx-build-container-images
    nodeset: ubuntu-bionic
    required-projects:
      - openstack/pbrx
    pre-run: playbooks/container-images/pre.yaml
    run: playbooks/container-images/run.yaml

- job:
    name: pbrx-build-zuul-containers
    parent: pbrx-build-container-images
    required-projects:
      - openstack-infra/zuul
    vars:
      zuul_work_dir: src/git.openstack.org/openstack-infra/zuul

- project:
    templates:
      - docs-on-readthedocs
      - publish-to-pypi
    vars:
      rtd_webhook_id: '42240'
    check:
      jobs:
        - tox-pep8
        - tox-py35
        - tox-py36:
            nodeset: ubuntu-bionic
        - pbrx-build-zuul-containers
    gate:
      jobs:
        - tox-pep8
        - tox-py35
        - tox-py36:
            nodeset: ubuntu-bionic
        - pbrx-build-zuul-containers
