- project:
    templates:
      - docs-on-readthedocs
      - publish-to-pypi
    vars:
      rtd_webhook_id: '42240'
    check:
      jobs:
        - tox-pep8
        - tox-py35
        - tox-py36:
            nodeset: ubuntu-bionic
    gate:
      jobs:
        - tox-pep8
        - tox-py35
        - tox-py36:
            nodeset: ubuntu-bionic
