- hosts: all
  tasks:

    - name: Build container image
      command: |
        pbrx --debug build-images \
        {{ pbrx_prefix is defined | ternary('--prefix=' + pbrx_prefix, '') }} \
        {{ pbrx_tag is defined | ternary('--tag=' + pbrx_tag, '') }}
      args:
        chdir: '{{ zuul_work_dir|default(zuul.project.src_dir) }}'

    - name: Output image information
      command: docker images
